### ISSUE TITLE
[Feature Request] DateTime clamp 

### ISSUE THREAD

**Issue by FMorschel** [jogboms/time.dart#52]
### Proposal
DateTime (maybe Duration as well?) clamp. Any suggestions are welcome. I just encountered a need for a DateTime clamp, perhaps this nullable option is not the best fit, but for my case it was.

### Inspiration
```dart
num clamp(num lowerLimit, num upperLimit);
```

### Actual implementation
```dart
extension ClampDateTime on DateTime {
  DateTime clamp({DateTime? min, DateTime? max}) {
    assert(
      ((min != null) && (max != null)) ? min.compareTo(max).isNegative : true,
      'DateTime min has to be before max\n(min: $min - max: $max)',
    );
    if ((min != null) && compareTo(min).isNegative) {
      return min;
    } else if ((max != null) && max.compareTo(this).isNegative) {
      return max;
    } else {
      return this;
    }
  }
}

extension DurationClamp on Duration{
  Duration clamp({Duration? min, Duration? max}) {
    assert(
      ((min != null) && (max != null)) ? min.compareTo(max).isNegative : true,
      'Duration min has to be shorter than max\n(min: $min - max: $max)',
    );
    if ((min != null) && compareTo(min).isNegative) {
      return min;
    } else if ((max != null) && max.compareTo(this).isNegative) {
      return max;
    } else {
      return this;
    }
  }
}
```

**Comment by jogboms** [comment]
Hey @FMorschel 
I like this and think it would be a nice addition. 
Like you mentioned, I would rather not have a nullable parameter because it just complicates the implementation when in real life if any of the limit is null you would check before hand but on second thought it does mean doing a comparison first before using the `clamp` utility which sort of defeats the whole point of wanting to use it in the first place: removing the need to over think about your own stuff.

Do make a PR and we can get this in. 👍
